/**
 * @fileoverview
 * PR body templates for openblock-registry submissions.
 */

/**
 * Generate PR body for publishing a new plugin or version
 * @param {object} options - PR options
 * @param {string} options.pluginId - Plugin ID
 * @param {string} options.pluginName - Plugin display name
 * @param {string} options.pluginType - Plugin type (device/extension)
 * @param {string} options.version - Version being published
 * @param {string} options.repository - GitHub repository URL
 * @param {string} options.description - Plugin description
 * @param {string} options.author - Author name
 * @param {boolean} options.isNewPlugin - Whether this is a new plugin
 * @returns {string} PR body markdown
 */
const generatePublishPRBody = options => {
    const {
        pluginId,
        pluginName,
        pluginType,
        version,
        repository,
        description,
        author,
        isNewPlugin
    } = options;

    const actionText = isNewPlugin ? 'Publish New Plugin' : 'Publish New Version';
    const typeLabel = pluginType === 'device' ? 'Device' : 'Extension';

    // Build basic info rows (same for both device and extension)
    const basicInfoRows = `| **Plugin ID** | \`${pluginId}\` |
| **Name** | ${pluginName} |
| **Type** | ${typeLabel} |
| **Version** | \`${version}\` |
| **Author** | ${author || '-'} |
| **Description** | ${description || '-'} |
| **Repository** | ${repository} |`;

    const body = `## ${actionText}: ${pluginName}

### Basic Information

| Field | Value |
|------|-----|
${basicInfoRows}

---

*This PR was automatically generated by [openblock-registry-cli](https://github.com/openblockcc/openblock-registry-cli)*
`;

    return body;
};

/**
 * Generate PR body for unpublishing a plugin version
 * @param {object} options - PR options
 * @param {string} options.pluginId - Plugin ID
 * @param {string} options.pluginName - Plugin display name
 * @param {string} options.version - Version to unpublish (or 'all')
 * @param {string} options.reason - Reason for unpublishing
 * @returns {string} PR body markdown
 */
const generateUnpublishPRBody = options => {
    const {
        pluginId,
        pluginName,
        version,
        reason
    } = options;

    const versionText = version === 'all' ? 'All Versions' : `v${version}`;

    return `## Unpublish: ${pluginName}

### Basic Information

| Field | Value |
|------|-----|
| **Plugin ID** | \`${pluginId}\` |
| **Unpublish Version** | ${versionText} |

### Reason for Unpublishing

${reason || 'No reason provided'}

### Important Notes

- After unpublishing, users who have installed this version can still continue to use it
- Resource files on R2 will be retained (not deleted)
- Only removed from the packages.json index

---

*This PR was automatically generated by [openblock-registry-cli](https://github.com/openblockcc/openblock-registry-cli)*
`;
};

/**
 * Generate PR title
 * @param {string} action - 'publish' or 'unpublish'
 * @param {string} pluginId - Plugin ID
 * @param {string} version - Version
 * @returns {string} PR title
 */
const generatePRTitle = (action, pluginId, version) => {
    if (action === 'publish') {
        return `[Publish] ${pluginId}@${version}`;
    }
    if (action === 'unpublish') {
        return `[Unpublish] ${pluginId}@${version}`;
    }
    return `[Update] ${pluginId}`;
};

module.exports = {
    generatePublishPRBody,
    generateUnpublishPRBody,
    generatePRTitle
};
